import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import Providers from '@/components/Providers';
import Navbar from '@/components/Navbar';
import './globals.css';

const roboto_mono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={`${roboto_mono.className} bg-bg-color text-text-color py-20 px-9`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
